#  HTGS8F Processing

- Whole genome sequence data; Illumina and Nanopore.
- Shipped and submitted to Plasmidsaurus ???.
- Data available on: ???.
- Started procecessing on: 11-25-25 on Poplar.

## Previous analysis
Data was previously downloaded to nspahr laptop (before direct download via Plasmidsaurus REST API was implemented) and a preliminary analysis was done there. Short read data was filtered/trimmed, and mutations were called against ADP1 and ACN2586. However, only the received and trimmed reads were uploaded to poplar. The samples in this order are of different lineages and should not all be compared to the same parent strain.

## Present analysis
I uploaded the data to poplar and initiated QA/QC (steps 1 and 2 in this notebook. These cells may not be executable any longer because the pipeline code has been continuously improved since starting the analysis). Later, I started mutation calling for a subset of the samples, i.e. those strains, that were of current interest because they were used in a robotic ALE experiment. This notebook can be used to run different batches of the samples against different references (at different time points.)

## Steps
1. Data organization, file renaming
    1.  Get data onto server.
    2.  Compress library folder (right-click, compress)
    3.  scp into my jupyter home: scp -prJ nspahr@logins.cels.anl.gov /Users/nataschaspahr/data/seq_data/Plasmidsaurus_10-06-2025_P4CYGL.zip nspahr@poplar.cels.anl.gov:/scratch1/fliu/hub_scratch/nspahr/
2. Short reads: QA/QC
3. Notebook set-up for current version of AISynbioPipeline code.
4. Creating seqsamples and cross-checking in LIMS.
5. Breseq: Batch 1 (Isolates of 5 different ACN3500 progeny strains)

## 1. Data organization

In [1]:
## Running on poplar
## Make sure running in appropriate kernel

import sys, os

# Must add environment's bin to the PATH inside the notebook
env_bin = os.path.join(os.path.dirname(sys.executable), "")
os.environ["PATH"] = env_bin + ":" + os.environ["PATH"]

# Must add ai_synbio repo to PATH
sys.path.append('/home/nspahr/code/ai_synbio_data_processing/')

In [2]:
# Reload magic command to ensure that changes made to my imported modules are being picked up by the notebook continuously

%load_ext autoreload
%autoreload 2

In [3]:
# Define AI-Synbio project data directories

LIB_DIR = '/storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/'
library = 'Plasmidsaurus_9-13-2025_HTGS8F'
lib_path = os.path.join(LIB_DIR, library)
shortlib = os.path.join(lib_path, os.path.basename(lib_path) + '_Illumina')
longlib = os.path.join(lib_path, os.path.basename(lib_path) + '_Nanopore')

In [4]:
# Define my Jupyter Hub home directories for viewing intermittent results

home_lib_path = os.path.join('/storage/nspahr/', 'lib_analysis', library)
os.makedirs(home_lib_path, exist_ok=True)

## 2. Short reads: QA/QC

In [5]:
short_received = os.path.join(shortlib, 'received')

In [10]:
import os
from binfo_utils import create_manifest

manifest = create_manifest(short_received, platform='plasmidsaurus_hybrid')
manifest

,sample_name,fwd_fastq,rvs_fastq
23,ANLstock.ACN2853.pyruvate.colony1,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
8,ANLstock.ACN2853.pyruvate.colony2,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
20,ANLstock.ACN2853.pyruvate.colony3,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
24,ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
25,ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
26,ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
19,ANLstock.ACN3210.pyruvate.colony1,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
22,ANLstock.ACN3210.pyruvate.colony2,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
21,ANLstock.ACN3210.pyruvate.colony3,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
16,ANLstock.ACN3560.colony1,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
5,ANLstock.ACN3560.colony2,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
2,ANLstock.ACN3560.colony3,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
13,ANLstock.ACN3575.colony1,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
6,ANLstock.ACN3575.colony2,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
0,ANLstock.ACN3575.colony3,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
9,ANLstock.ACN3577.colony1,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
14,ANLstock.ACN3577.colony2,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
11,ANLstock.ACN3577.colony3,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
12,ANLstock.ACN3578.colony1,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
7,ANLstock.ACN3578.colony2,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
17,ANLstock.ACN3578.colony3,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
18,ANLstock.ACN3579.colony1,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
15,ANLstock.ACN3579.colony2,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
3,ANLstock.ACN3579.colony3,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
1,ANLstock.ADP1.colony1,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
10,ANLstock.ADP1.colony2,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
4,ANLstock.ADP1.colony3,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...

### QC of received

In [11]:
from read_qc import run_fastqc
from binfo_utils import create_manifest

manifest = create_manifest(short_received, platform='plasmidsaurus_hybrid')

[run_fastqc(f) for f in manifest['fwd_fastq']]
[run_fastqc(f) for f in manifest['rvs_fastq']]

Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN3560.colony1_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN3560.colony1_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN3560.colony2_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN3560.colony2_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN3560.colony3_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN3560.colony3_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN3575.colony1_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN3575.colony1_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN3575.colony2_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN3575.colony2_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN3575.colony3_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN3575.colony3_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN3577.colony1_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN3577.colony1_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN3577.colony2_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN3577.colony2_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN3577.colony3_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN3577.colony3_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN3578.colony1_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN3578.colony1_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN3578.colony2_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN3578.colony2_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN3578.colony3_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN3578.colony3_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN3579.colony1_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN3579.colony1_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN3579.colony2_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN3579.colony2_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ACN3579.colony3_illumina_R1.fastq.gz

Analysis complete for ANLstock.ACN3579.colony3_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ADP1.colony1_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ADP1.colony1_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ADP1.colony1_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ADP1.colony1_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ADP1.colony1_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ADP1.colony1_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ADP1.colony1_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ADP1.colony1_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ADP1.colony1_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ADP1.colony1_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ADP1.colony1_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ADP1.colony1_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ADP1.colony1_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ADP1.colony1_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ADP1.colony1_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ADP1.colony1_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ADP1.colony1_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ADP1.colony1_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ADP1.colony1_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ADP1.colony1_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ADP1.colony1_illumina_R1.fastq.gz

Analysis complete for ANLstock.ADP1.colony1_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ADP1.colony2_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ADP1.colony2_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ADP1.colony2_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ADP1.colony2_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ADP1.colony2_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ADP1.colony2_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ADP1.colony2_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ADP1.colony2_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ADP1.colony2_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ADP1.colony2_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ADP1.colony2_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ADP1.colony2_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ADP1.colony2_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ADP1.colony2_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ADP1.colony2_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ADP1.colony2_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ADP1.colony2_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ADP1.colony2_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ADP1.colony2_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ADP1.colony2_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ADP1.colony2_illumina_R1.fastq.gz

Analysis complete for ANLstock.ADP1.colony2_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ADP1.colony3_illumina_R1.fastq.gz
application/gzip

Started analysis of ANLstock.ADP1.colony3_illumina_R1.fastq.gz
Approx 5% complete for ANLstock.ADP1.colony3_illumina_R1.fastq.gz
Approx 10% complete for ANLstock.ADP1.colony3_illumina_R1.fastq.gz
Approx 15% complete for ANLstock.ADP1.colony3_illumina_R1.fastq.gz
Approx 20% complete for ANLstock.ADP1.colony3_illumina_R1.fastq.gz
Approx 25% complete for ANLstock.ADP1.colony3_illumina_R1.fastq.gz
Approx 30% complete for ANLstock.ADP1.colony3_illumina_R1.fastq.gz
Approx 35% complete for ANLstock.ADP1.colony3_illumina_R1.fastq.gz
Approx 40% complete for ANLstock.ADP1.colony3_illumina_R1.fastq.gz
Approx 45% complete for ANLstock.ADP1.colony3_illumina_R1.fastq.gz
Approx 50% complete for ANLstock.ADP1.colony3_illumina_R1.fastq.gz
Approx 55% complete for ANLstock.ADP1.colony3_illumina_R1.fastq.gz
Approx 60% complete for ANLstock.ADP1.colony3_illumina_R1.fastq.gz
Approx 65% complete for ANLstock.ADP1.colony3_illumina_R1.fastq.gz
Approx 70% complete for ANLstock.ADP1.colony3_illumina_R1.fastq.gz
Approx 75% complete for ANLstock.ADP1.colony3_illumina_R1.fastq.gz
Approx 80% complete for ANLstock.ADP1.colony3_illumina_R1.fastq.gz
Approx 85% complete for ANLstock.ADP1.colony3_illumina_R1.fastq.gz
Approx 90% complete for ANLstock.ADP1.colony3_illumina_R1.fastq.gz
Approx 95% complete for ANLstock.ADP1.colony3_illumina_R1.fastq.gz

Analysis complete for ANLstock.ADP1.colony3_illumina_R1.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853.pyruvate.colony1_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853.pyruvate.colony1_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN3560.colony1_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN3560.colony1_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN3560.colony2_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN3560.colony2_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN3560.colony3_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN3560.colony3_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN3575.colony1_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN3575.colony1_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN3575.colony2_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN3575.colony2_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN3575.colony3_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN3575.colony3_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN3577.colony1_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN3577.colony1_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN3577.colony2_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN3577.colony2_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN3577.colony3_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN3577.colony3_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN3578.colony1_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN3578.colony1_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN3578.colony2_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN3578.colony2_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN3578.colony3_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN3578.colony3_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN3579.colony1_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN3579.colony1_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN3579.colony2_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN3579.colony2_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ACN3579.colony3_illumina_R2.fastq.gz

Analysis complete for ANLstock.ACN3579.colony3_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ADP1.colony1_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ADP1.colony1_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ADP1.colony1_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ADP1.colony1_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ADP1.colony1_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ADP1.colony1_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ADP1.colony1_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ADP1.colony1_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ADP1.colony1_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ADP1.colony1_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ADP1.colony1_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ADP1.colony1_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ADP1.colony1_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ADP1.colony1_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ADP1.colony1_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ADP1.colony1_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ADP1.colony1_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ADP1.colony1_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ADP1.colony1_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ADP1.colony1_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ADP1.colony1_illumina_R2.fastq.gz

Analysis complete for ANLstock.ADP1.colony1_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ADP1.colony2_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ADP1.colony2_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ADP1.colony2_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ADP1.colony2_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ADP1.colony2_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ADP1.colony2_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ADP1.colony2_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ADP1.colony2_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ADP1.colony2_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ADP1.colony2_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ADP1.colony2_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ADP1.colony2_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ADP1.colony2_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ADP1.colony2_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ADP1.colony2_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ADP1.colony2_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ADP1.colony2_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ADP1.colony2_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ADP1.colony2_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ADP1.colony2_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ADP1.colony2_illumina_R2.fastq.gz

Analysis complete for ANLstock.ADP1.colony2_illumina_R2.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ADP1.colony3_illumina_R2.fastq.gz
application/gzip

Started analysis of ANLstock.ADP1.colony3_illumina_R2.fastq.gz
Approx 5% complete for ANLstock.ADP1.colony3_illumina_R2.fastq.gz
Approx 10% complete for ANLstock.ADP1.colony3_illumina_R2.fastq.gz
Approx 15% complete for ANLstock.ADP1.colony3_illumina_R2.fastq.gz
Approx 20% complete for ANLstock.ADP1.colony3_illumina_R2.fastq.gz
Approx 25% complete for ANLstock.ADP1.colony3_illumina_R2.fastq.gz
Approx 30% complete for ANLstock.ADP1.colony3_illumina_R2.fastq.gz
Approx 35% complete for ANLstock.ADP1.colony3_illumina_R2.fastq.gz
Approx 40% complete for ANLstock.ADP1.colony3_illumina_R2.fastq.gz
Approx 45% complete for ANLstock.ADP1.colony3_illumina_R2.fastq.gz
Approx 50% complete for ANLstock.ADP1.colony3_illumina_R2.fastq.gz
Approx 55% complete for ANLstock.ADP1.colony3_illumina_R2.fastq.gz
Approx 60% complete for ANLstock.ADP1.colony3_illumina_R2.fastq.gz
Approx 65% complete for ANLstock.ADP1.colony3_illumina_R2.fastq.gz
Approx 70% complete for ANLstock.ADP1.colony3_illumina_R2.fastq.gz
Approx 75% complete for ANLstock.ADP1.colony3_illumina_R2.fastq.gz
Approx 80% complete for ANLstock.ADP1.colony3_illumina_R2.fastq.gz
Approx 85% complete for ANLstock.ADP1.colony3_illumina_R2.fastq.gz
Approx 90% complete for ANLstock.ADP1.colony3_illumina_R2.fastq.gz
Approx 95% complete for ANLstock.ADP1.colony3_illumina_R2.fastq.gz

Analysis complete for ANLstock.ADP1.colony3_illumina_R2.fastq.gz

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [12]:
from read_qc import run_multiqc
import shutil

multiqc_report = run_multiqc(short_received)
shutil.copy(multiqc_report, home_lib_path)

/// ]8;id=442942;https://multiqc.info\MultiQC]8;;\ v1.32

       file_search | Search path: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received

        searching | ████████████████████████████████████████ 100% 162/162                                                   html

            fastqc | Found 54 reports
     write_results | Data        : multiqc_data
     write_results | Report      : multiqc_report.html
           multiqc | MultiQC complete

'/storage/nspahr/lib_analysis/Plasmidsaurus_9-13-2025_HTGS8F/multiqc_report.html'

### Trimming with fastp

In [6]:
import subprocess
from binfo_utils import create_manifest
from read_qc import run_fastp

short_trimmed = os.path.join(shortlib, 'trimmed')
os.makedirs(short_trimmed, exist_ok=True)

manifest = create_manifest(short_received, platform='plasmidsaurus_hybrid')

for index, row in manifest.iterrows():
    read1_in_path = row['fwd_fastq']
    read2_in_path = row['rvs_fastq']
    read1_in_basename = os.path.basename(read1_in_path)
    read2_in_basename = os.path.basename(read2_in_path)
    read1_out_path = os.path.join(short_trimmed, read1_in_basename.replace('.fastq.gz', '_trimmed.fastq.gz'))
    read2_out_path = os.path.join(short_trimmed, read2_in_basename.replace('.fastq.gz', '_trimmed.fastq.gz'))
    run_fastp(read1_in_path, read2_in_path, read1_out_path, read2_out_path, threads=16, polyG=6)

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853.pyruvate.colony1_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 23250157
total bases: 3510773707
Q20 bases: 3490850780(99.4325%)
Q30 bases: 3420290284(97.4227%)
Q40 bases: 3420290284(97.4227%)

Read2 before filtering:
total reads: 23250157
total bases: 3510773707
Q20 bases: 3456335737(98.4494%)
Q30 bases: 3308704727(94.2443%)
Q40 bases: 3308704727(94.2443%)

Read1 after filtering:
total reads: 23045981
total bases: 3462024147
Q20 bases: 3447959457(99.5937%)
Q30 bases: 3385120403(97.7786%)
Q40 bases: 3385120403(97.7786%)

Read2 after filtering:
total reads: 23045981
total bases: 3462024147
Q20 bases: 3422953164(98.8714%)
Q30 bases: 3287496311(94.9588%)
Q40 bases: 3287496311(94.9588%)

Filtering result:
reads passed filter: 46091962
reads failed due to low quality: 398754
reads failed due to too many N: 9598
reads failed due to too short: 0
reads with adapter trimmed: 768174
bases trimmed due to adapters: 35882350

Duplication rate: 28.8134%

Insert size peak (evaluated by paired-end reads): 271

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony1_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony1_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853.pyruvate.colony1_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853.pyruvate.colony1_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony1_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony1_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 56 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853.pyruvate.colony2_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 28188720
total bases: 4256496720
Q20 bases: 4232558285(99.4376%)
Q30 bases: 4143831942(97.3531%)
Q40 bases: 4143831942(97.3531%)

Read2 before filtering:
total reads: 28188720
total bases: 4256496720
Q20 bases: 4189872923(98.4348%)
Q30 bases: 4009534451(94.198%)
Q40 bases: 4009534451(94.198%)

Read1 after filtering:
total reads: 27934938
total bases: 4197294851
Q20 bases: 4179707067(99.581%)
Q30 bases: 4099794846(97.6771%)
Q40 bases: 4099794846(97.6771%)

Read2 after filtering:
total reads: 27934938
total bases: 4197294851
Q20 bases: 4150049843(98.8744%)
Q30 bases: 3984713140(94.9353%)
Q40 bases: 3984713140(94.9353%)

Filtering result:
reads passed filter: 55869876
reads failed due to low quality: 495916
reads failed due to too many N: 11648
reads failed due to too short: 0
reads with adapter trimmed: 887140
bases trimmed due to adapters: 41806374

Duplication rate: 27.1442%

Insert size peak (evaluated by paired-end reads): 271

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony2_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony2_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853.pyruvate.colony2_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853.pyruvate.colony2_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony2_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony2_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 65 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 30176192
total bases: 4556604992
Q20 bases: 4530700583(99.4315%)
Q30 bases: 4439490030(97.4298%)
Q40 bases: 4439490030(97.4298%)

Read2 before filtering:
total reads: 30176192
total bases: 4556604992
Q20 bases: 4493935280(98.6246%)
Q30 bases: 4317846581(94.7602%)
Q40 bases: 4317846581(94.7602%)

Read1 after filtering:
total reads: 29935063
total bases: 4496652176
Q20 bases: 4478534161(99.5971%)
Q30 bases: 4396707079(97.7773%)
Q40 bases: 4396707079(97.7773%)

Read2 after filtering:
total reads: 29935063
total bases: 4496652176
Q20 bases: 4452111884(99.0095%)
Q30 bases: 4290251044(95.4099%)
Q40 bases: 4290251044(95.4099%)

Filtering result:
reads passed filter: 59870126
reads failed due to low quality: 469844
reads failed due to too many N: 12414
reads failed due to too short: 0
reads with adapter trimmed: 991168
bases trimmed due to adapters: 47131938

Duplication rate: 28.7788%

Insert size peak (evaluated by paired-end reads): 271

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony3_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony3_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853.pyruvate.colony3_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853.pyruvate.colony3_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony3_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony3_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 75 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 20798861
total bases: 3140628011
Q20 bases: 3122653951(99.4277%)
Q30 bases: 3055522579(97.2902%)
Q40 bases: 3055522579(97.2902%)

Read2 before filtering:
total reads: 20798861
total bases: 3140628011
Q20 bases: 3098969761(98.6736%)
Q30 bases: 2980369191(94.8972%)
Q40 bases: 2980369191(94.8972%)

Read1 after filtering:
total reads: 20646987
total bases: 3088374953
Q20 bases: 3075288485(99.5763%)
Q30 bases: 3015318503(97.6345%)
Q40 bases: 3015318503(97.6345%)

Read2 after filtering:
total reads: 20646987
total bases: 3088374953
Q20 bases: 3058153926(99.0215%)
Q30 bases: 2948742277(95.4788%)
Q40 bases: 2948742277(95.4788%)

Filtering result:
reads passed filter: 41293974
reads failed due to low quality: 295084
reads failed due to too many N: 8664
reads failed due to too short: 0
reads with adapter trimmed: 1192022
bases trimmed due to adapters: 58702052

Duplication rate: 22.871%

Insert size peak (evaluated by paired-end reads): 271

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 51 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 31339553
total bases: 4732272503
Q20 bases: 4705362178(99.4313%)
Q30 bases: 4604493742(97.2998%)
Q40 bases: 4604493742(97.2998%)

Read2 before filtering:
total reads: 31339553
total bases: 4732272503
Q20 bases: 4654246574(98.3512%)
Q30 bases: 4442762451(93.8822%)
Q40 bases: 4442762451(93.8822%)

Read1 after filtering:
total reads: 31055905
total bases: 4666461521
Q20 bases: 4646531129(99.5729%)
Q30 bases: 4555471398(97.6215%)
Q40 bases: 4555471398(97.6215%)

Read2 after filtering:
total reads: 31055905
total bases: 4666461521
Q20 bases: 4610066777(98.7915%)
Q30 bases: 4415443470(94.6208%)
Q40 bases: 4415443470(94.6208%)

Filtering result:
reads passed filter: 62111810
reads failed due to low quality: 554360
reads failed due to too many N: 12936
reads failed due to too short: 0
reads with adapter trimmed: 957710
bases trimmed due to adapters: 46013108

Duplication rate: 27.2176%

Insert size peak (evaluated by paired-end reads): 271

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 72 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 10603550
total bases: 1601136050
Q20 bases: 1590545098(99.3385%)
Q30 bases: 1551818810(96.9199%)
Q40 bases: 1551818810(96.9199%)

Read2 before filtering:
total reads: 10603550
total bases: 1601136050
Q20 bases: 1575841919(98.4202%)
Q30 bases: 1507003385(94.1209%)
Q40 bases: 1507003385(94.1209%)

Read1 after filtering:
total reads: 10507525
total bases: 1569825634
Q20 bases: 1562424882(99.5286%)
Q30 bases: 1528187647(97.3476%)
Q40 bases: 1528187647(97.3476%)

Read2 after filtering:
total reads: 10507525
total bases: 1569825634
Q20 bases: 1552071545(98.869%)
Q30 bases: 1489193467(94.8636%)
Q40 bases: 1489193467(94.8636%)

Filtering result:
reads passed filter: 21015050
reads failed due to low quality: 187898
reads failed due to too many N: 4152
reads failed due to too short: 0
reads with adapter trimmed: 682508
bases trimmed due to adapters: 33675204

Duplication rate: 21.3794%

Insert size peak (evaluated by paired-end reads): 268

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 25 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 22309049
total bases: 3368666399
Q20 bases: 3350417228(99.4583%)
Q30 bases: 3283673660(97.477%)
Q40 bases: 3283673660(97.477%)

Read2 before filtering:
total reads: 22309049
total bases: 3368666399
Q20 bases: 3310574804(98.2755%)
Q30 bases: 3157196465(93.7224%)
Q40 bases: 3157196465(93.7224%)

Read1 after filtering:
total reads: 22086855
total bases: 3321149599
Q20 bases: 3307949149(99.6025%)
Q30 bases: 3248359453(97.8083%)
Q40 bases: 3248359453(97.8083%)

Read2 after filtering:
total reads: 22086855
total bases: 3321149599
Q20 bases: 3280235220(98.7681%)
Q30 bases: 3140517818(94.5612%)
Q40 bases: 3140517818(94.5612%)

Filtering result:
reads passed filter: 44173710
reads failed due to low quality: 435254
reads failed due to too many N: 9134
reads failed due to too short: 0
reads with adapter trimmed: 599632
bases trimmed due to adapters: 27959786

Duplication rate: 25.5806%

Insert size peak (evaluated by paired-end reads): 270

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony1_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony1_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3210.pyruvate.colony1_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3210.pyruvate.colony1_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony1_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony1_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 53 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 28940596
total bases: 4370029996
Q20 bases: 4345571228(99.4403%)
Q30 bases: 4255806626(97.3862%)
Q40 bases: 4255806626(97.3862%)

Read2 before filtering:
total reads: 28940596
total bases: 4370029996
Q20 bases: 4309760043(98.6208%)
Q30 bases: 4140686826(94.7519%)
Q40 bases: 4140686826(94.7519%)

Read1 after filtering:
total reads: 28712850
total bases: 4313763474
Q20 bases: 4295728761(99.5819%)
Q30 bases: 4214638905(97.7021%)
Q40 bases: 4214638905(97.7021%)

Read2 after filtering:
total reads: 28712850
total bases: 4313763474
Q20 bases: 4270668147(99.001%)
Q30 bases: 4115051895(95.3935%)
Q40 bases: 4115051895(95.3935%)

Filtering result:
reads passed filter: 57425700
reads failed due to low quality: 443456
reads failed due to too many N: 12036
reads failed due to too short: 0
reads with adapter trimmed: 918272
bases trimmed due to adapters: 43795318

Duplication rate: 26.1711%

Insert size peak (evaluated by paired-end reads): 271

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony2_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony2_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3210.pyruvate.colony2_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3210.pyruvate.colony2_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony2_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony2_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 66 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 21550134
total bases: 3254070234
Q20 bases: 3233585434(99.3705%)
Q30 bases: 3156258068(96.9942%)
Q40 bases: 3156258068(96.9942%)

Read2 before filtering:
total reads: 21550134
total bases: 3254070234
Q20 bases: 3214331280(98.7788%)
Q30 bases: 3098458919(95.2179%)
Q40 bases: 3098458919(95.2179%)

Read1 after filtering:
total reads: 21393365
total bases: 3214739490
Q20 bases: 3199267802(99.5187%)
Q30 bases: 3128073144(97.3041%)
Q40 bases: 3128073144(97.3041%)

Read2 after filtering:
total reads: 21393365
total bases: 3214739490
Q20 bases: 3186761035(99.1297%)
Q30 bases: 3080401991(95.8212%)
Q40 bases: 3080401991(95.8212%)

Filtering result:
reads passed filter: 42786730
reads failed due to low quality: 304638
reads failed due to too many N: 8900
reads failed due to too short: 0
reads with adapter trimmed: 666656
bases trimmed due to adapters: 31344738

Duplication rate: 25.5816%

Insert size peak (evaluated by paired-end reads): 271

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony3_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony3_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3210.pyruvate.colony3_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3210.pyruvate.colony3_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony3_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony3_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 50 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3560.colony1_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3560.colony1_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 16732197
total bases: 2526561747
Q20 bases: 2509007899(99.3052%)
Q30 bases: 2452558745(97.071%)
Q40 bases: 2452558745(97.071%)

Read2 before filtering:
total reads: 16732197
total bases: 2526561747
Q20 bases: 2491861835(98.6266%)
Q30 bases: 2396518317(94.8529%)
Q40 bases: 2396518317(94.8529%)

Read1 after filtering:
total reads: 16594881
total bases: 2468227732
Q20 bases: 2457609772(99.5698%)
Q30 bases: 2410338734(97.6546%)
Q40 bases: 2410338734(97.6546%)

Read2 after filtering:
total reads: 16594881
total bases: 2468227732
Q20 bases: 2444140571(99.0241%)
Q30 bases: 2357411677(95.5103%)
Q40 bases: 2357411677(95.5103%)

Filtering result:
reads passed filter: 33189762
reads failed due to low quality: 267730
reads failed due to too many N: 6902
reads failed due to too short: 0
reads with adapter trimmed: 1488310
bases trimmed due to adapters: 75253726

Duplication rate: 21.4371%

Insert size peak (evaluated by paired-end reads): 271

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony1_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony1_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3560.colony1_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3560.colony1_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony1_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony1_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 37 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3560.colony2_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3560.colony2_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 30063686
total bases: 4539616586
Q20 bases: 4511584469(99.3825%)
Q30 bases: 4403008589(96.9908%)
Q40 bases: 4403008589(96.9908%)

Read2 before filtering:
total reads: 30063686
total bases: 4539616586
Q20 bases: 4464534271(98.3461%)
Q30 bases: 4257166090(93.7781%)
Q40 bases: 4257166090(93.7781%)

Read1 after filtering:
total reads: 29807058
total bases: 4479912401
Q20 bases: 4458423613(99.5203%)
Q30 bases: 4358949624(97.2999%)
Q40 bases: 4358949624(97.2999%)

Read2 after filtering:
total reads: 29807058
total bases: 4479912401
Q20 bases: 4424142222(98.7551%)
Q30 bases: 4231921780(94.4644%)
Q40 bases: 4231921780(94.4644%)

Filtering result:
reads passed filter: 59614116
reads failed due to low quality: 501056
reads failed due to too many N: 12200
reads failed due to too short: 0
reads with adapter trimmed: 876194
bases trimmed due to adapters: 41949352

Duplication rate: 25.8963%

Insert size peak (evaluated by paired-end reads): 270

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony2_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony2_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3560.colony2_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3560.colony2_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony2_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony2_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 74 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3560.colony3_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3560.colony3_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 14004655
total bases: 2114702905
Q20 bases: 2100310483(99.3194%)
Q30 bases: 2053818700(97.1209%)
Q40 bases: 2053818700(97.1209%)

Read2 before filtering:
total reads: 14004655
total bases: 2114702905
Q20 bases: 2086741221(98.6777%)
Q30 bases: 2008290734(94.968%)
Q40 bases: 2008290734(94.968%)

Read1 after filtering:
total reads: 13898168
total bases: 2073116821
Q20 bases: 2064057357(99.563%)
Q30 bases: 2023896078(97.6258%)
Q40 bases: 2023896078(97.6258%)

Read2 after filtering:
total reads: 13898168
total bases: 2073116821
Q20 bases: 2053270124(99.0427%)
Q30 bases: 1981377150(95.5748%)
Q40 bases: 1981377150(95.5748%)

Filtering result:
reads passed filter: 27796336
reads failed due to low quality: 207342
reads failed due to too many N: 5632
reads failed due to too short: 0
reads with adapter trimmed: 1033372
bases trimmed due to adapters: 51067918

Duplication rate: 21.3194%

Insert size peak (evaluated by paired-end reads): 271

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony3_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony3_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3560.colony3_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3560.colony3_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony3_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony3_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 35 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3575.colony1_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3575.colony1_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 24858036
total bases: 3753563436
Q20 bases: 3731920837(99.4234%)
Q30 bases: 3652254158(97.301%)
Q40 bases: 3652254158(97.301%)

Read2 before filtering:
total reads: 24858036
total bases: 3753563436
Q20 bases: 3704147840(98.6835%)
Q30 bases: 3562732686(94.916%)
Q40 bases: 3562732686(94.916%)

Read1 after filtering:
total reads: 24673748
total bases: 3699065979
Q20 bases: 3683639909(99.583%)
Q30 bases: 3612243647(97.6529%)
Q40 bases: 3612243647(97.6529%)

Read2 after filtering:
total reads: 24673748
total bases: 3699065979
Q20 bases: 3663543907(99.0397%)
Q30 bases: 3533215515(95.5164%)
Q40 bases: 3533215515(95.5164%)

Filtering result:
reads passed filter: 49347496
reads failed due to low quality: 358074
reads failed due to too many N: 10502
reads failed due to too short: 0
reads with adapter trimmed: 1107690
bases trimmed due to adapters: 53394838

Duplication rate: 24.2293%

Insert size peak (evaluated by paired-end reads): 270

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony1_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony1_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3575.colony1_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3575.colony1_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony1_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony1_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 55 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3575.colony2_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3575.colony2_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 25288591
total bases: 3818577241
Q20 bases: 3797549494(99.4493%)
Q30 bases: 3716288486(97.3213%)
Q40 bases: 3716288486(97.3213%)

Read2 before filtering:
total reads: 25288591
total bases: 3818577241
Q20 bases: 3765561904(98.6116%)
Q30 bases: 3613781506(94.6369%)
Q40 bases: 3613781506(94.6369%)

Read1 after filtering:
total reads: 25100860
total bases: 3770339431
Q20 bases: 3754422472(99.5778%)
Q30 bases: 3680252302(97.6106%)
Q40 bases: 3680252302(97.6106%)

Read2 after filtering:
total reads: 25100860
total bases: 3770339431
Q20 bases: 3731454321(98.9687%)
Q30 bases: 3590855089(95.2396%)
Q40 bases: 3590855089(95.2396%)

Filtering result:
reads passed filter: 50201720
reads failed due to low quality: 365084
reads failed due to too many N: 10378
reads failed due to too short: 0
reads with adapter trimmed: 836032
bases trimmed due to adapters: 39822738

Duplication rate: 23.6081%

Insert size peak (evaluated by paired-end reads): 271

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony2_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony2_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3575.colony2_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3575.colony2_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony2_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony2_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 54 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3575.colony3_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3575.colony3_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 31967945
total bases: 4827159695
Q20 bases: 4791713132(99.2657%)
Q30 bases: 4649239388(96.3142%)
Q40 bases: 4649239388(96.3142%)

Read2 before filtering:
total reads: 31967945
total bases: 4827159695
Q20 bases: 4758114192(98.5696%)
Q30 bases: 4558992017(94.4446%)
Q40 bases: 4558992017(94.4446%)

Read1 after filtering:
total reads: 31736335
total bases: 4770947149
Q20 bases: 4742385774(99.4013%)
Q30 bases: 4608366590(96.5923%)
Q40 bases: 4608366590(96.5923%)

Read2 after filtering:
total reads: 31736335
total bases: 4770947149
Q20 bases: 4718720666(98.9053%)
Q30 bases: 4532771659(95.0078%)
Q40 bases: 4532771659(95.0078%)

Filtering result:
reads passed filter: 63472670
reads failed due to low quality: 451058
reads failed due to too many N: 12162
reads failed due to too short: 0
reads with adapter trimmed: 910348
bases trimmed due to adapters: 42519960

Duplication rate: 26.7176%

Insert size peak (evaluated by paired-end reads): 271

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony3_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony3_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3575.colony3_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3575.colony3_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony3_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony3_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 67 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3577.colony1_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3577.colony1_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 29440983
total bases: 4445588433
Q20 bases: 4417305132(99.3638%)
Q30 bases: 4307611320(96.8963%)
Q40 bases: 4307611320(96.8963%)

Read2 before filtering:
total reads: 29440983
total bases: 4445588433
Q20 bases: 4377693742(98.4728%)
Q30 bases: 4188015284(94.2061%)
Q40 bases: 4188015284(94.2061%)

Read1 after filtering:
total reads: 29190756
total bases: 4387536231
Q20 bases: 4365781535(99.5042%)
Q30 bases: 4264756949(97.2016%)
Q40 bases: 4264756949(97.2016%)

Read2 after filtering:
total reads: 29190756
total bases: 4387536231
Q20 bases: 4338455004(98.8813%)
Q30 bases: 4163366291(94.8908%)
Q40 bases: 4163366291(94.8908%)

Filtering result:
reads passed filter: 58381512
reads failed due to low quality: 488330
reads failed due to too many N: 12124
reads failed due to too short: 0
reads with adapter trimmed: 855484
bases trimmed due to adapters: 40573742

Duplication rate: 29.7622%

Insert size peak (evaluated by paired-end reads): 270

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony1_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony1_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3577.colony1_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3577.colony1_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony1_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony1_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 67 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3577.colony2_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3577.colony2_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 18907564
total bases: 2855042164
Q20 bases: 2837701374(99.3926%)
Q30 bases: 2777529908(97.2851%)
Q40 bases: 2777529908(97.2851%)

Read2 before filtering:
total reads: 18907564
total bases: 2855042164
Q20 bases: 2814427025(98.5774%)
Q30 bases: 2701969436(94.6385%)
Q40 bases: 2701969436(94.6385%)

Read1 after filtering:
total reads: 18753260
total bases: 2813263987
Q20 bases: 2801183395(99.5706%)
Q30 bases: 2747771284(97.672%)
Q40 bases: 2747771284(97.672%)

Read2 after filtering:
total reads: 18753260
total bases: 2813263987
Q20 bases: 2784224230(98.9678%)
Q30 bases: 2680980765(95.2979%)
Q40 bases: 2680980765(95.2979%)

Filtering result:
reads passed filter: 37506520
reads failed due to low quality: 300648
reads failed due to too many N: 7960
reads failed due to too short: 0
reads with adapter trimmed: 759086
bases trimmed due to adapters: 36994694

Duplication rate: 25.805%

Insert size peak (evaluated by paired-end reads): 271

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony2_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony2_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3577.colony2_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3577.colony2_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony2_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony2_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony2_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 40 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3577.colony3_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3577.colony3_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 9288660
total bases: 1402587660
Q20 bases: 1393034761(99.3189%)
Q30 bases: 1362099636(97.1133%)
Q40 bases: 1362099636(97.1133%)

Read2 before filtering:
total reads: 9288660
total bases: 1402587660
Q20 bases: 1384243937(98.6922%)
Q30 bases: 1333339504(95.0628%)
Q40 bases: 1333339504(95.0628%)

Read1 after filtering:
total reads: 9212990
total bases: 1372794469
Q20 bases: 1366744622(99.5593%)
Q30 bases: 1340386934(97.6393%)
Q40 bases: 1340386934(97.6393%)

Read2 after filtering:
total reads: 9212990
total bases: 1372794469
Q20 bases: 1360176178(99.0808%)
Q30 bases: 1313969262(95.7149%)
Q40 bases: 1313969262(95.7149%)

Filtering result:
reads passed filter: 18425980
reads failed due to low quality: 147416
reads failed due to too many N: 3924
reads failed due to too short: 0
reads with adapter trimmed: 741458
bases trimmed due to adapters: 36774908

Duplication rate: 22.8275%

Insert size peak (evaluated by paired-end reads): 271

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony3_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony3_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3577.colony3_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3577.colony3_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony3_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony3_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony3_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 20 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3578.colony1_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3578.colony1_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 21960525
total bases: 3316039275
Q20 bases: 3295384393(99.3771%)
Q30 bases: 3222466985(97.1782%)
Q40 bases: 3222466985(97.1782%)

Read2 before filtering:
total reads: 21960525
total bases: 3316039275
Q20 bases: 3264302814(98.4398%)
Q30 bases: 3126855583(94.2949%)
Q40 bases: 3126855583(94.2949%)

Read1 after filtering:
total reads: 21744955
total bases: 3263721857
Q20 bases: 3249058593(99.5507%)
Q30 bases: 3184159318(97.5622%)
Q40 bases: 3184159318(97.5622%)

Read2 after filtering:
total reads: 21744955
total bases: 3263721857
Q20 bases: 3228352449(98.9163%)
Q30 bases: 3103720323(95.0976%)
Q40 bases: 3103720323(95.0976%)

Filtering result:
reads passed filter: 43489910
reads failed due to low quality: 422204
reads failed due to too many N: 8936
reads failed due to too short: 0
reads with adapter trimmed: 828206
bases trimmed due to adapters: 39575636

Duplication rate: 25.3751%

Insert size peak (evaluated by paired-end reads): 271

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony1_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony1_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3578.colony1_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3578.colony1_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony1_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony1_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 47 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3578.colony2_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3578.colony2_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 1866741
total bases: 281877891
Q20 bases: 280323708(99.4486%)
Q30 bases: 274493487(97.3803%)
Q40 bases: 274493487(97.3803%)

Read2 before filtering:
total reads: 1866741
total bases: 281877891
Q20 bases: 277933560(98.6007%)
Q30 bases: 266857412(94.6713%)
Q40 bases: 266857412(94.6713%)

Read1 after filtering:
total reads: 1852126
total bases: 278172031
Q20 bases: 277026157(99.5881%)
Q30 bases: 271753542(97.6926%)
Q40 bases: 271753542(97.6926%)

Read2 after filtering:
total reads: 1852126
total bases: 278172031
Q20 bases: 275333817(98.9797%)
Q30 bases: 265124240(95.3095%)
Q40 bases: 265124240(95.3095%)

Filtering result:
reads passed filter: 3704252
reads failed due to low quality: 28412
reads failed due to too many N: 818
reads failed due to too short: 0
reads with adapter trimmed: 63152
bases trimmed due to adapters: 3000598

Duplication rate: 20.1902%

Insert size peak (evaluated by paired-end reads): 249

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony2_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony2_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3578.colony2_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3578.colony2_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony2_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony2_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 5 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3578.colony3_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3578.colony3_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 37054598
total bases: 5595244298
Q20 bases: 5562958284(99.423%)
Q30 bases: 5446998182(97.3505%)
Q40 bases: 5446998182(97.3505%)

Read2 before filtering:
total reads: 37054598
total bases: 5595244298
Q20 bases: 5503742849(98.3647%)
Q30 bases: 5260256024(94.013%)
Q40 bases: 5260256024(94.013%)

Read1 after filtering:
total reads: 36694090
total bases: 5517438926
Q20 bases: 5494332898(99.5812%)
Q30 bases: 5390186953(97.6936%)
Q40 bases: 5390186953(97.6936%)

Read2 after filtering:
total reads: 36694090
total bases: 5517438926
Q20 bases: 5453543741(98.8419%)
Q30 bases: 5231169257(94.8115%)
Q40 bases: 5231169257(94.8115%)

Filtering result:
reads passed filter: 73388180
reads failed due to low quality: 706200
reads failed due to too many N: 14816
reads failed due to too short: 0
reads with adapter trimmed: 994964
bases trimmed due to adapters: 46767554

Duplication rate: 29.7286%

Insert size peak (evaluated by paired-end reads): 271

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony3_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony3_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3578.colony3_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3578.colony3_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony3_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony3_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 86 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3579.colony1_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3579.colony1_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 26745041
total bases: 4038501191
Q20 bases: 4013497710(99.3809%)
Q30 bases: 3926766389(97.2333%)
Q40 bases: 3926766389(97.2333%)

Read2 before filtering:
total reads: 26745041
total bases: 4038501191
Q20 bases: 3976723947(98.4703%)
Q30 bases: 3809715940(94.3349%)
Q40 bases: 3809715940(94.3349%)

Read1 after filtering:
total reads: 26496962
total bases: 3974600355
Q20 bases: 3957883212(99.5794%)
Q30 bases: 3881622438(97.6607%)
Q40 bases: 3881622438(97.6607%)

Read2 after filtering:
total reads: 26496962
total bases: 3974600355
Q20 bases: 3931718222(98.9211%)
Q30 bases: 3779545471(95.0925%)
Q40 bases: 3779545471(95.0925%)

Filtering result:
reads passed filter: 52993924
reads failed due to low quality: 485302
reads failed due to too many N: 10856
reads failed due to too short: 0
reads with adapter trimmed: 1096752
bases trimmed due to adapters: 52942626

Duplication rate: 24.9007%

Insert size peak (evaluated by paired-end reads): 271

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony1_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony1_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3579.colony1_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3579.colony1_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony1_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony1_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 63 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3579.colony2_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3579.colony2_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 11893592
total bases: 1795932392
Q20 bases: 1783524912(99.3091%)
Q30 bases: 1741594107(96.9744%)
Q40 bases: 1741594107(96.9744%)

Read2 before filtering:
total reads: 11893592
total bases: 1795932392
Q20 bases: 1770774054(98.5991%)
Q30 bases: 1700047770(94.661%)
Q40 bases: 1700047770(94.661%)

Read1 after filtering:
total reads: 11802351
total bases: 1757043138
Q20 bases: 1749195915(99.5534%)
Q30 bases: 1713285528(97.5096%)
Q40 bases: 1713285528(97.5096%)

Read2 after filtering:
total reads: 11802351
total bases: 1757043138
Q20 bases: 1738873769(98.9659%)
Q30 bases: 1673839039(95.2645%)
Q40 bases: 1673839039(95.2645%)

Filtering result:
reads passed filter: 23604702
reads failed due to low quality: 177524
reads failed due to too many N: 4958
reads failed due to too short: 0
reads with adapter trimmed: 995204
bases trimmed due to adapters: 50267322

Duplication rate: 21.0295%

Insert size peak (evaluated by paired-end reads): 271

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony2_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony2_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3579.colony2_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3579.colony2_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony2_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony2_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 31 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3579.colony3_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3579.colony3_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 20451236
total bases: 3088136636
Q20 bases: 3070312168(99.4228%)
Q30 bases: 3007482421(97.3883%)
Q40 bases: 3007482421(97.3883%)

Read2 before filtering:
total reads: 20451236
total bases: 3088136636
Q20 bases: 3039406266(98.422%)
Q30 bases: 2906396689(94.1149%)
Q40 bases: 2906396689(94.1149%)

Read1 after filtering:
total reads: 20270860
total bases: 3046304372
Q20 bases: 3033756730(99.5881%)
Q30 bases: 2977626186(97.7455%)
Q40 bases: 2977626186(97.7455%)

Read2 after filtering:
total reads: 20270860
total bases: 3046304372
Q20 bases: 3011160616(98.8463%)
Q30 bases: 2888809613(94.83%)
Q40 bases: 2888809613(94.83%)

Filtering result:
reads passed filter: 40541720
reads failed due to low quality: 352312
reads failed due to too many N: 8440
reads failed due to too short: 0
reads with adapter trimmed: 615678
bases trimmed due to adapters: 29230330

Duplication rate: 25.1884%

Insert size peak (evaluated by paired-end reads): 271

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony3_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony3_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3579.colony3_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ACN3579.colony3_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony3_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony3_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 49 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ADP1.colony1_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ADP1.colony1_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 18213769
total bases: 2750279119
Q20 bases: 2732843031(99.366%)
Q30 bases: 2668137761(97.0133%)
Q40 bases: 2668137761(97.0133%)

Read2 before filtering:
total reads: 18213769
total bases: 2750279119
Q20 bases: 2715369793(98.7307%)
Q30 bases: 2614941749(95.0791%)
Q40 bases: 2614941749(95.0791%)

Read1 after filtering:
total reads: 18082706
total bases: 2716555217
Q20 bases: 2703458995(99.5179%)
Q30 bases: 2643817358(97.3224%)
Q40 bases: 2643817358(97.3224%)

Read2 after filtering:
total reads: 18082706
total bases: 2716555217
Q20 bases: 2691302363(99.0704%)
Q30 bases: 2598363443(95.6492%)
Q40 bases: 2598363443(95.6492%)

Filtering result:
reads passed filter: 36165412
reads failed due to low quality: 254504
reads failed due to too many N: 7622
reads failed due to too short: 0
reads with adapter trimmed: 606552
bases trimmed due to adapters: 27892168

Duplication rate: 24.0088%

Insert size peak (evaluated by paired-end reads): 271

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony1_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony1_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ADP1.colony1_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ADP1.colony1_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony1_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony1_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 45 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ADP1.colony2_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ADP1.colony2_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 16118349
total bases: 2433870699
Q20 bases: 2420549056(99.4527%)
Q30 bases: 2369928469(97.3728%)
Q40 bases: 2369928469(97.3728%)

Read2 before filtering:
total reads: 16118349
total bases: 2433870699
Q20 bases: 2397199171(98.4933%)
Q30 bases: 2295606068(94.3191%)
Q40 bases: 2295606068(94.3191%)

Read1 after filtering:
total reads: 15987744
total bases: 2405620087
Q20 bases: 2395397092(99.575%)
Q30 bases: 2349054721(97.6486%)
Q40 bases: 2349054721(97.6486%)

Read2 after filtering:
total reads: 15987744
total bases: 2405620087
Q20 bases: 2378681246(98.8802%)
Q30 bases: 2284716432(94.9741%)
Q40 bases: 2284716432(94.9741%)

Filtering result:
reads passed filter: 31975488
reads failed due to low quality: 254456
reads failed due to too many N: 6754
reads failed due to too short: 0
reads with adapter trimmed: 375180
bases trimmed due to adapters: 17074030

Duplication rate: 23.7301%

Insert size peak (evaluated by paired-end reads): 268

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony2_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony2_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ADP1.colony2_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ADP1.colony2_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony2_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony2_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 39 seconds

Running fastp on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ADP1.colony3_illumina_R1.fastq.gz and /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ADP1.colony3_illumina_R2.fastq.gz

Read1 before filtering:
total reads: 22375952
total bases: 3378768752
Q20 bases: 3357146716(99.3601%)
Q30 bases: 3276341421(96.9685%)
Q40 bases: 3276341421(96.9685%)

Read2 before filtering:
total reads: 22375952
total bases: 3378768752
Q20 bases: 3329438495(98.54%)
Q30 bases: 3193037100(94.503%)
Q40 bases: 3193037100(94.503%)

Read1 after filtering:
total reads: 22182662
total bases: 3333517891
Q20 bases: 3317272318(99.5127%)
Q30 bases: 3243316063(97.2941%)
Q40 bases: 3243316063(97.2941%)

Read2 after filtering:
total reads: 22182662
total bases: 3333517891
Q20 bases: 3298568673(98.9516%)
Q30 bases: 3173299928(95.1937%)
Q40 bases: 3173299928(95.1937%)

Filtering result:
reads passed filter: 44365324
reads failed due to low quality: 377758
reads failed due to too many N: 8822
reads failed due to too short: 0
reads with adapter trimmed: 687330
bases trimmed due to adapters: 32160244

Duplication rate: 25.3608%

Insert size peak (evaluated by paired-end reads): 271

JSON report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony3_illumina_fastp.json
HTML report: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony3_illumina_fastp.html

fastp -i /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ADP1.colony3_illumina_R1.fastq.gz -I /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/received/ANLstock.ADP1.colony3_illumina_R2.fastq.gz -o /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz -O /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz -w 16 -j /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony3_illumina_fastp.json -h /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony3_illumina_fastp.html --poly_g_min_len 6
fastp v1.0.1, time used: 54 seconds

### QC of fastp-trimmed

In [7]:
from read_qc import run_fastqc
from binfo_utils import create_manifest

manifest = create_manifest(short_trimmed, platform='plasmidsaurus_hybrid')

[run_fastqc(f) for f in manifest['fwd_fastq']]
[run_fastqc(f) for f in manifest['rvs_fastq']]

Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3560.colony1_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3560.colony2_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3560.colony3_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3575.colony1_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3575.colony2_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3575.colony3_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3577.colony1_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3577.colony2_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3577.colony3_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3578.colony1_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3578.colony2_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3578.colony3_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3579.colony1_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3579.colony2_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3579.colony3_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ADP1.colony1_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ADP1.colony2_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
Approx 5% complete for ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
Approx 10% complete for ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
Approx 15% complete for ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
Approx 20% complete for ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
Approx 25% complete for ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
Approx 30% complete for ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
Approx 35% complete for ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
Approx 40% complete for ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
Approx 45% complete for ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
Approx 50% complete for ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
Approx 55% complete for ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
Approx 60% complete for ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
Approx 65% complete for ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
Approx 70% complete for ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
Approx 75% complete for ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
Approx 80% complete for ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
Approx 85% complete for ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
Approx 90% complete for ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
Approx 95% complete for ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz

Analysis complete for ANLstock.ADP1.colony3_illumina_R1_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN2853.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN2853.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN2853.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3210.pyruvate.colony1_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3210.pyruvate.colony2_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3210.pyruvate.colony3_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3560.colony1_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3560.colony2_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3560.colony3_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3575.colony1_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3575.colony2_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3575.colony3_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3577.colony1_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3577.colony2_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3577.colony2_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3577.colony2_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3577.colony2_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3577.colony2_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3577.colony2_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3577.colony2_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3577.colony2_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3577.colony2_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3577.colony3_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3577.colony3_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3577.colony3_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3577.colony3_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3577.colony3_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3577.colony3_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3578.colony1_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3578.colony2_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3578.colony3_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3579.colony1_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3579.colony2_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ACN3579.colony3_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ADP1.colony1_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ADP1.colony2_illumina_R2_trimmed.fastq.gz
Running FastQC on /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed/ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz
application/gzip

Started analysis of ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz
Approx 5% complete for ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz
Approx 10% complete for ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz
Approx 15% complete for ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz
Approx 20% complete for ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz
Approx 25% complete for ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz
Approx 30% complete for ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz
Approx 35% complete for ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz
Approx 40% complete for ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz
Approx 45% complete for ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz
Approx 50% complete for ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz
Approx 55% complete for ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz
Approx 60% complete for ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz
Approx 65% complete for ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz
Approx 70% complete for ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz
Approx 75% complete for ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz
Approx 80% complete for ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz
Approx 85% complete for ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz
Approx 90% complete for ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz
Approx 95% complete for ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz

Analysis complete for ANLstock.ADP1.colony3_illumina_R2_trimmed.fastq.gz

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [8]:
from read_qc import run_multiqc
import shutil

multiqc_report = run_multiqc(short_trimmed)
shutil.copy(multiqc_report, os.path.join(home_lib_path, 'short_trimmed_multiqc_report.html'))

/// ]8;id=262134;https://multiqc.info\MultiQC]8;;\ v1.32

       file_search | Search path: /storage/synbio/ai_synbio_data/experimental_data/sequencing_libraries/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/trimmed

        searching | ████████████████████████████████████████ 100% 216/216                                                   html

             fastp | Found 27 reports
            fastqc | Found 54 reports
     write_results | Data        : multiqc_data
     write_results | Report      : multiqc_report.html
           multiqc | MultiQC complete

'/storage/nspahr/lib_analysis/Plasmidsaurus_9-13-2025_HTGS8F/short_trimmed_multiqc_report.html'

**Results**
FastQC is terribly slow, but reports duplication levels and specifically indicates adapter sequences left after trimming. Not sure how to assess this without fastQC.

## 3. Notebook set-up

In [ ]:
## Make sure running in aisynbio_env

In [1]:
# Reload magic command to ensure that changes made to my imported modules are being picked up by the notebook continuously

%load_ext autoreload
%autoreload 2

In [2]:
import sys
import os

# Add project root to path for access to workflows and tasks
notebook_dir = os.getcwd()
project_root = os.path.dirname(notebook_dir)

if project_root not in sys.path:
    sys.path.insert(0, project_root)

In [3]:
import os

# Must add environment's bin to the PATH inside the notebook
env_bin = os.path.join(os.path.dirname(sys.executable), "")
os.environ["PATH"] = env_bin + ":" + os.environ["PATH"]

In [4]:
from aisynbiopipeline.workflows.seq_folder_utils import list_seqorders

list_seqorders()

['Plasmidsaurus_9-13-2025_HTGS8F',
 'Plasmidsaurus_10-06-2025_P4CYGL',
 'ANL_ALE1b',
 'mock_SeqOrder_12-04-25',
 'Plasmidsaurus_2025-12-22_MQRBN8',
 'Plasmidsaurus_2025-09-30_P4CYGL',
 'Plasmidsaurus_2026-01-13_S2SVV5']

In [5]:
# Create seqorder name, make reception folder and seqorder analysis folder in nspahr homedir

from aisynbiopipeline.workflows.plasmidsaurus import create_seqorder_name
from aisynbiopipeline.workflows.seq_folder_utils import list_seqorders, SeqOrder, Library, SeqSample
import os

item_code = 'HTGS8F'
seqorder_name = 'Plasmidsaurus_9-13-2025_HTGS8F'

home_dir = '/storage/nspahr/lib_analysis/' + seqorder_name
breseq_ACN3500_dir = home_dir + '/breseq_analysis_ACN3500'
os.makedirs(breseq_ACN3500_dir, exist_ok=True)

In [6]:
# Define seqorder

seqorder = SeqOrder(seqorder_name)
short = Library(seqorder, 'Illumina')

## 4. Cross-checking this Plasmidsaurus order seqsamples in LIMS and creating SeqSamples.

In [7]:
short_manifest = short.create_manifest('received')
short_manifest

,sample_name,R1,R2
0,ANLstock.ACN2853.pyruvate.colony1,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
1,ANLstock.ACN2853.pyruvate.colony2,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
2,ANLstock.ACN2853.pyruvate.colony3,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
3,ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony1,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
4,ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony2,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
5,ANLstock.ACN2853_T_dgoA-Best.pyruvate.colony3,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
6,ANLstock.ACN3210.pyruvate.colony1,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
7,ANLstock.ACN3210.pyruvate.colony2,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
8,ANLstock.ACN3210.pyruvate.colony3,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
9,ANLstock.ACN3560.colony1,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
10,ANLstock.ACN3560.colony2,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
11,ANLstock.ACN3560.colony3,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
12,ANLstock.ACN3575.colony1,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
13,ANLstock.ACN3575.colony2,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
14,ANLstock.ACN3575.colony3,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
15,ANLstock.ACN3577.colony1,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
16,ANLstock.ACN3577.colony2,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
17,ANLstock.ACN3577.colony3,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
18,ANLstock.ACN3578.colony1,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
19,ANLstock.ACN3578.colony2,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
20,ANLstock.ACN3578.colony3,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
21,ANLstock.ACN3579.colony1,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
22,ANLstock.ACN3579.colony2,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
23,ANLstock.ACN3579.colony3,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
24,ANLstock.ADP1.colony1,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
25,ANLstock.ADP1.colony2,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...
26,ANLstock.ADP1.colony3,/storage/synbio/ai_synbio_data/experimental_da...,/storage/synbio/ai_synbio_data/experimental_da...

In [8]:
# Import LIMS utilities (use util_simple.py for standalone LIMS API usage)

%run util_simple.py

✓ LIMS API loaded successfully

In [9]:
# Run a manual LIMS mirror db sync

from aisynbiopipeline.limsapi.sync import sync_all_sheets

sync_all_sheets()

2026-02-11 04:20:32,372 - lims_sync - INFO - Starting sync operation
2026-02-11 04:20:32,373 - lims_sync - INFO - Connecting to Google Sheets
2026-02-11 04:20:33,147 - lims_sync - INFO - Connecting to database
2026-02-11 04:20:33,455 - lims_sync - INFO - Found 15 worksheets: Experiments, Strains, Conditions, Samples, Measurements, Genes, Measurement_types, DNA_constructs, Primers, dgoA_alleles_new, dgoA_alleles_old, robotic_mt_samples, Wells, Strain_stocks_ANL, Plasmid_stocks_ANL
2026-02-11 04:20:33,456 - lims_sync - INFO - Syncing worksheet: Experiments
2026-02-11 04:20:34,746 - lims_sync - INFO - Retrieved 11 rows from Experiments
2026-02-11 04:20:34,879 - lims_sync - INFO - Inserted 3, updated 0 rows in Experiments
2026-02-11 04:20:34,893 - lims_sync - INFO - Marked 1 rows as deleted in Experiments
2026-02-11 04:20:39,894 - lims_sync - INFO - Syncing worksheet: Strains
2026-02-11 04:20:41,039 - lims_sync - INFO - Retrieved 1020 rows from Strains
2026-02-11 04:20:41,198 - lims_sync - INFO - Inserted 14, updated 0 rows in Strains
2026-02-11 04:20:41,221 - lims_sync - INFO - Marked 13 rows as deleted in Strains
2026-02-11 04:20:46,222 - lims_sync - INFO - Syncing worksheet: Conditions
2026-02-11 04:20:47,175 - lims_sync - INFO - Retrieved 16 rows from Conditions
2026-02-11 04:20:47,247 - lims_sync - INFO - Inserted 0, updated 0 rows in Conditions
2026-02-11 04:20:52,255 - lims_sync - INFO - Syncing worksheet: Samples
2026-02-11 04:20:53,197 - lims_sync - INFO - Retrieved 292 rows from Samples
2026-02-11 04:20:53,655 - lims_sync - INFO - Inserted 167, updated 0 rows in Samples
2026-02-11 04:20:53,673 - lims_sync - INFO - Marked 1 rows as deleted in Samples
2026-02-11 04:20:58,674 - lims_sync - INFO - Syncing worksheet: Measurements
2026-02-11 04:20:59,687 - lims_sync - INFO - Retrieved 1154 rows from Measurements
2026-02-11 04:21:02,420 - lims_sync - INFO - Inserted 163, updated 0 rows in Measurements
2026-02-11 04:21:02,451 - lims_sync - INFO - Marked 12 rows as deleted in Measurements
2026-02-11 04:21:07,451 - lims_sync - INFO - Syncing worksheet: Genes
2026-02-11 04:21:10,348 - lims_sync - INFO - Retrieved 3356 rows from Genes
2026-02-11 04:21:24,195 - lims_sync - INFO - Inserted 11, updated 0 rows in Genes
2026-02-11 04:21:24,285 - lims_sync - INFO - Marked 11 rows as deleted in Genes
2026-02-11 04:21:29,286 - lims_sync - INFO - Syncing worksheet: Measurement_types
2026-02-11 04:21:30,136 - lims_sync - INFO - Retrieved 10 rows from Measurement_types
2026-02-11 04:21:30,173 - lims_sync - INFO - Inserted 0, updated 0 rows in Measurement_types
2026-02-11 04:21:35,180 - lims_sync - INFO - Syncing worksheet: DNA_constructs
2026-02-11 04:21:36,141 - lims_sync - INFO - Retrieved 10 rows from DNA_constructs
2026-02-11 04:21:36,159 - lims_sync - INFO - Inserted 10, updated 0 rows in DNA_constructs
2026-02-11 04:21:36,171 - lims_sync - INFO - Marked 10 rows as deleted in DNA_constructs
2026-02-11 04:21:41,172 - lims_sync - INFO - Syncing worksheet: Primers
2026-02-11 04:21:42,063 - lims_sync - INFO - Retrieved 8 rows from Primers
2026-02-11 04:21:42,096 - lims_sync - INFO - Inserted 0, updated 0 rows in Primers
2026-02-11 04:21:47,103 - lims_sync - INFO - Syncing worksheet: dgoA_alleles_new
2026-02-11 04:21:47,909 - lims_sync - INFO - Retrieved 10 rows from dgoA_alleles_new
2026-02-11 04:21:47,951 - lims_sync - INFO - Inserted 0, updated 0 rows in dgoA_alleles_new
2026-02-11 04:21:52,958 - lims_sync - INFO - Syncing worksheet: dgoA_alleles_old
2026-02-11 04:21:54,070 - lims_sync - INFO - Retrieved 3 rows from dgoA_alleles_old
2026-02-11 04:21:54,083 - lims_sync - INFO - Inserted 0, updated 0 rows in dgoA_alleles_old
2026-02-11 04:21:59,090 - lims_sync - INFO - Syncing worksheet: robotic_mt_samples
2026-02-11 04:21:59,982 - lims_sync - INFO - Retrieved 203 rows from robotic_mt_samples
2026-02-11 04:22:00,011 - lims_sync - INFO - Inserted 203, updated 0 rows in robotic_mt_samples
2026-02-11 04:22:05,020 - lims_sync - INFO - Syncing worksheet: Wells
2026-02-11 04:22:05,896 - lims_sync - INFO - Retrieved 96 rows from Wells
2026-02-11 04:22:05,918 - lims_sync - INFO - Inserted 96, updated 0 rows in Wells
2026-02-11 04:22:10,927 - lims_sync - INFO - Syncing worksheet: Strain_stocks_ANL
2026-02-11 04:22:11,803 - lims_sync - INFO - Retrieved 52 rows from Strain_stocks_ANL
2026-02-11 04:22:12,014 - lims_sync - INFO - Inserted 2, updated 0 rows in Strain_stocks_ANL
2026-02-11 04:22:17,023 - lims_sync - INFO - Syncing worksheet: Plasmid_stocks_ANL
2026-02-11 04:22:18,159 - lims_sync - INFO - Retrieved 3 rows from Plasmid_stocks_ANL
2026-02-11 04:22:18,460 - lims_sync - INFO - Inserted 3, updated 0 rows in Plasmid_stocks_ANL
2026-02-11 04:22:18,509 - lims_sync - INFO - Sync completed successfully. Synced 15 tables, inserted 672, updated 0, deleted 48 rows

{'start_time': '2026-02-11T04:20:32.372872',
 'end_time': '2026-02-11T04:22:18.509420',
 'success': True,
 'tables_synced': 15,
 'total_rows_inserted': 672,
 'total_rows_updated': 0,
 'total_rows_deleted': 48,
 'errors': []}

In [12]:
# Cross-checking seq sample measurement names

thisExpLIMSseqsamples_short = query_lims(
    'Measurements',
    filters={'Experiment': 'strain_stocks', 'Type': 'Short_DNA_reads'}
)['Name'].to_list()

# thisExpLIMSseqsamples_long = query_lims(
#     'Measurements',
#     filters={'Experiment': 'strain_stocks', 'Type': 'Long_DNA_reads'}
# )['Name'].to_list()

print(f"Are all short Plasmidsaurus seqsamples from order {item_code} in the LIMS?")
print(all([x in thisExpLIMSseqsamples_short for x in short_manifest['sample_name'].to_list()]))
print(f"Are all short LIMS seqsamples with selected filters in Plasmidsaurus order {item_code}?")
print(all([x in short_manifest['sample_name'].to_list() for x in thisExpLIMSseqsamples_short]))

# long_manifest = long.create_manifest('received')
# print(f"Are all Plasmidsaurus long seqsamples from order {item_code} in the LIMS?")
# print(all([x in thisExpLIMSseqsamples_long for x in long_manifest['sample_name'].to_list()]))
# print(f"Are all LIMS long seqsamples with selected filters in Plasmidsaurus order {item_code}?")
# print(all([x in long_manifest['sample_name'].to_list() for x in thisExpLIMSseqsamples_long]))

Are all short Plasmidsaurus seqsamples from order HTGS8F in the LIMS?
False
Are all short LIMS seqsamples with selected filters in Plasmidsaurus order HTGS8F?
False

NameError: name 'long' is not defined

## 5. Breseq: Batch 1 (Isolates of 5 different ACN3500 progeny strains)

Run breseq:
3 colonies each of 3560, 3575, 3577, 3578, and 3579 against ACN3500_NSS.gbk ref genome

In [52]:
# Creating batch (list) of short seqsamples for this seqorder

seqsamples = [SeqSample(short, row['sample_name']) for _, row in short_manifest.iloc[9:24].iterrows()]

In [14]:
from aisynbiopipeline.workflows.reference_utils import list_reference_genomes

list_reference_genomes()

['ADP1_Neidle_CDM.gbk',
 'ACN2821_CDM.gbk',
 'ACN2586_NSS.gbk',
 'ACN3500_IRZ.gbk',
 'ACN3500_NSS.gbk']

In [ ]:
## To run breseq celery worksers, activate micromamba, then call worker script:
"""
cd ~/code/AISynbioPipeline
export PATH="/opt/micromamba/bin/:$PATH"
eval "$(micromamba shell hook --shell bash)"
micromamba activate
micromamba activate aisynbio_env
python -m aisynbiopipeline.tasks.breseq_task 7
"""

In [ ]:
# 6 breseq workers were already running. I am adding a 7th, hoping that it will be designated to the HTGS8F samples (hidden from currently running samples?):

# (aisynbio_env) nspahr@seed:~/code/AISynbioPipeline$ python -m aisynbiopipeline.tasks.breseq_task 1
# (aisynbio_env) nspahr@seed:~/code/AISynbioPipeline$ python -m aisynbiopipeline.tasks.breseq_task 2
# (aisynbio_env) nspahr@seed:~/code/AISynbioPipeline$ python -m aisynbiopipeline.tasks.breseq_task 3
# (aisynbio_env) nspahr@seed:~/code/AISynbioPipeline$ python -m aisynbiopipeline.tasks.breseq_task 4
# (aisynbio_env) nspahr@seed:~/code/AISynbioPipeline$ python -m aisynbiopipeline.tasks.breseq_task 5
# (aisynbio_env) nspahr@seed:~/code/AISynbioPipeline$ python -m aisynbiopipeline.tasks.breseq_task 6
# (aisynbio_env) nspahr@seed:~/code/AISynbioPipeline$ python -m aisynbiopipeline.tasks.breseq_task 7

In [18]:
# Where should this code go?

# Specifies and assigns breseq parameters

from pathlib import Path

def define_breseq_params(seqsample, ref_filename, poly=True, fold_coverage=300, num_processors=4):

    # Normalize Path → str - Celery tasks only accept certain input data types.
    def norm(x): return str(x) if isinstance(x, Path) else x
    
    breseq_params = {
        'read_paths': [norm(x) for x in seqsample.trimmed],
        'breseq_folder': norm(seqsample.breseq),
        'reference': ref_filename,
        'polymorphism_prediction': poly,
        'limit_fold_coverage': fold_coverage,
        'num_processors': num_processors
    }
    return breseq_params

In [19]:
from celery import Celery
import os

# Create Celery client
client = Celery(
    'client',
    broker=os.getenv('CELERY_BROKER_URL', 'redis://bioseed_redis:6379/10'),
    backend=os.getenv('CELERY_RESULT_BACKEND', 'redis://bioseed_redis:6379/10')
)

# Submit tasks

results = []

for sample in seqsamples:
    result = client.send_task(
        'breseq.run',
        kwargs=define_breseq_params(sample, ref_filename='ACN3500_NSS.gbk'),
        queue='breseq'
    )
    results.append(result)

In [28]:
sum([(r.status=='SUCCESS') for r in results])

ValueError: Exception information must include the exception type

In [27]:
for i in results:
    print(i.status)
# for i in results:
#     print(i.result) ## Check version_name to make sure it's different from previous version name

SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS
SUCCESS

ValueError: Exception information must include the exception type

In [31]:
from aisynbiopipeline.workflows.breseq import Breseq

breseq_objects = []

for s in seqsamples:
    breseq_folder = s.library.path / 'breseq' / s.sample_name/ 'breseq_df1972644b'
    b = Breseq.from_existing(breseq_folder)
    breseq_objects.append(b)

In [34]:
for b in breseq_objects:
    print(b.title, b.exists)

ANLstock.ACN3560.colony1 True
ANLstock.ACN3560.colony2 True
ANLstock.ACN3560.colony3 True
ANLstock.ACN3575.colony1 True
ANLstock.ACN3575.colony2 True
ANLstock.ACN3575.colony3 True
ANLstock.ACN3577.colony1 True
ANLstock.ACN3577.colony2 False
ANLstock.ACN3577.colony3 True
ANLstock.ACN3578.colony1 True
ANLstock.ACN3578.colony2 True
ANLstock.ACN3578.colony3 True
ANLstock.ACN3579.colony1 True
ANLstock.ACN3579.colony2 True
ANLstock.ACN3579.colony3 True

In [35]:
failed_seqsamples = []
for b in breseq_objects:
    if not os.path.exists(b.gd_file):
        failed_name = b.title
        print(failed_name)
        failed_seqsamples.append(SeqSample(short, failed_name))

ANLstock.ACN3577.colony2

In [37]:
# Re-running failed seqsamples

import shutil
from celery import Celery
import os

for f in failed_seqsamples:
    shutil.rmtree(f.breseq / 'breseq_df1972644b')

# Create Celery client
client = Celery(
    'client',
    broker=os.getenv('CELERY_BROKER_URL', 'redis://bioseed_redis:6379/10'),
    backend=os.getenv('CELERY_RESULT_BACKEND', 'redis://bioseed_redis:6379/10')
)

# Submit tasks

results = []

for sample in failed_seqsamples:
    result = client.send_task(
        'breseq.run',
        kwargs=define_breseq_params(sample, ref_filename='ACN3500_NSS.gbk'),
        queue='breseq'
    )
    results.append(result)

In [39]:
for i in results:
    print(i.status)

SUCCESS

### 3500 samples
- Create summary csv (including ver cassette coverage) and html comparison.
- Write files to 3500 breseq analysis subdir (breseq_analysis_ACN3500_NSS/).
- Create subfolder with symlinks to breseq output.

In [40]:
from aisynbiopipeline.workflows.breseq import Breseq

def create_breseq_summary(seqsample_batch, version_name, output_path, regions=None):
    
    breseq_objects = []
    
    for s in seqsample_batch:
        breseq_folder = s.library.path / 'breseq' / s.sample_name/ version_name
        b = Breseq.from_existing(breseq_folder)
        breseq_objects.append(b)
    
    rows = []
    
    for b in breseq_objects:
        
        row = {}
        
        try:
            b.count_reads()
            b.count_mutations()
            b.avg_coverage
            if regions:
                for key, value in regions.items():
                    b.get_region_average_coverage(value)
        except Exception as e:
            row.update({'seqsample': getattr(b, 'title', None)})
            # row.update(parse_seqsample_name(getattr(b, 'title', None)))
            row.update({'error': str(e),
                        'input_read_count': None,
                        'used_read_count': None,
                        'mapped_read_count': None,
                        'consensus_mutation_count': None,
                        'polymorphism_mutation_count': None,
                        'average_cov': None,}
                        )
            if regions:
                for key, value in regions.items():
                    row.update({key: None})
            rows.append(row)
            print(f"Error loading Breseq from {b.title}: {e}")
            continue
    
        row['seqsample'] = getattr(b, 'title', None)
        # row.update(parse_seqsample_name(getattr(b, 'title', None)))
        row['error'] = None
        row['input_read_count'] = getattr(b, 'input_read_count', None)
        row['used_read_count'] = getattr(b, 'used_read_count', None)
        row['mapped_read_count'] = getattr(b, 'mapped_read_count', None)
        row['consensus_mutation_count'] = getattr(b, 'consensus_mutation_count', None)
        row['polymorphism_mutation_count'] = getattr(b, 'polymorphism_mutation_count', None)
        row['average_cov'] = getattr(b, 'avg_coverage', None)
        if regions:
            for key, value in regions.items():
                row[key] = getattr(b, 'get_region_average_coverage', None)(value)
        rows.append(row)
    
    breseq_summary = pd.DataFrame(rows)
    
    if regions:
        for key, value in regions.items():
            breseq_summary[key+'_CN'] = breseq_summary[key]/breseq_summary['average_cov']

    # Write breseq run summary to csv
    breseq_summary.to_csv(output_path)
    
    return breseq_summary

In [41]:
def create_html_comparison(seqsample_batch, version_name, output_path):

    from aisynbiopipeline.workflows.breseq import compare_gdiff

    breseq_objects = []
    
    for s in seqsample_batch:
        breseq_folder = s.library.path / 'breseq' / s.sample_name/ version_name
        b = Breseq.from_existing(breseq_folder)
        breseq_objects.append(b)

    reference = b.params.reference
    gdiffs = [b.gd_file for b in breseq_objects]

    table_format = 'html'
    html = compare_gdiff(reference, output_path, gdiffs, format=table_format)

    return html

In [48]:
from aisynbiopipeline.workflows.reference_utils import genomic_region_from_features

def get_region_parameter(genbank_file, feature_first, feature_last):
    genome, start, stop = genomic_region_from_features(genbank_file, feature_first, feature_last)
    region = genome + ":" + str(start) + "-" + str(stop)
    return region

In [42]:
breseq_ACN3500_dir = home_dir + '/breseq_analysis_ACN3500/breseq_analysis_ACN3500_NSS/'
os.makedirs(breseq_ACN3500_dir)

In [44]:
from aisynbiopipeline.workflows.reference_utils import get_ref_genomes_path

genome3500_NSS = os.path.join(get_ref_genomes_path(), 'ACN3500_NSS.gbk')

In [58]:
# These strains are supposed to have the 6007 bp promoter deletion, including verR and parts of verB.
# Therefore, defining 'ver cassette' as verA through omega KmR cassette.

regions = {
    'ver_cassette': get_region_parameter(genome3500_NSS, 'omega KmR cassette', 'verA')
}

regions

{'ver_cassette': 'ACN3500_NSS:941311-948914'}

In [59]:
regions_to_include = ['ver_cassette']
regions_sub = {key:regions[key] for key in regions_to_include if key in regions}

In [60]:
create_breseq_summary(seqsamples, 'breseq_df1972644b', os.path.join(breseq_ACN3500_dir, 'mutation_summary_ACN3500_NSS.csv'), regions_sub)
create_html_comparison(seqsamples, 'breseq_df1972644b', os.path.join(breseq_ACN3500_dir, 'mutation_comparison_ACN3500_NSS.html'))

================================================================================
breseq 0.39.0     http://barricklab.org/breseq

Active Developers: Barrick JE, Deatherage DE
Contact:           <jeffrey.e.barrick@gmail.com>

breseq is free software; you can redistribute it and/or modify it under the
terms the GNU General Public License as published by the Free Software
Foundation; either version 2, or (at your option) any later version.

Copyright (c) 2008-2010 Michigan State University
Copyright (c) 2011-2022 The University of Texas at Austin

If you use breseq in your research, please cite:

  Deatherage, D.E., Barrick, J.E. (2014) Identification of mutations
  in laboratory-evolved microbes from next-generation sequencing
  data using breseq. Methods Mol. Biol. 1151: 165–188.

If you use structural variation (junction) predictions, please cite:

  Barrick, J.E., Colburn, G., Deatherage D.E., Traverse, C.C.,
  Strand, M.D., Borges, J.J., Knoester, D.B., Reba, A., Meyer, A.G.
  (2014) Identifying structural variation in haploid microbial genomes
  from short-read resequencing data using breseq. BMC Genomics 15:1039.
================================================================================

*** Begin ANNOTATE/COMPARE ***

    Reading input reference sequence files
        /storage/synbio/ai_synbio_data/reference_data/genomes/ACN3500_NSS.gbk

    Reading input GD file: /storage/synbio/ai_synbio_data/experimental_data/sequencing_orders/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/breseq/ANLstock.ACN3560.colony1/breseq_df1972644b/data/output.gd

    Reading input GD file: /storage/synbio/ai_synbio_data/experimental_data/sequencing_orders/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/breseq/ANLstock.ACN3560.colony2/breseq_df1972644b/data/output.gd

    Reading input GD file: /storage/synbio/ai_synbio_data/experimental_data/sequencing_orders/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/breseq/ANLstock.ACN3560.colony3/breseq_df1972644b/data/output.gd

    Reading input GD file: /storage/synbio/ai_synbio_data/experimental_data/sequencing_orders/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/breseq/ANLstock.ACN3575.colony1/breseq_df1972644b/data/output.gd

    Reading input GD file: /storage/synbio/ai_synbio_data/experimental_data/sequencing_orders/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/breseq/ANLstock.ACN3575.colony2/breseq_df1972644b/data/output.gd

    Reading input GD file: /storage/synbio/ai_synbio_data/experimental_data/sequencing_orders/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/breseq/ANLstock.ACN3575.colony3/breseq_df1972644b/data/output.gd

    Reading input GD file: /storage/synbio/ai_synbio_data/experimental_data/sequencing_orders/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/breseq/ANLstock.ACN3577.colony1/breseq_df1972644b/data/output.gd

    Reading input GD file: /storage/synbio/ai_synbio_data/experimental_data/sequencing_orders/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/breseq/ANLstock.ACN3577.colony2/breseq_df1972644b/data/output.gd

    Reading input GD file: /storage/synbio/ai_synbio_data/experimental_data/sequencing_orders/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/breseq/ANLstock.ACN3577.colony3/breseq_df1972644b/data/output.gd

    Reading input GD file: /storage/synbio/ai_synbio_data/experimental_data/sequencing_orders/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/breseq/ANLstock.ACN3578.colony1/breseq_df1972644b/data/output.gd

    Reading input GD file: /storage/synbio/ai_synbio_data/experimental_data/sequencing_orders/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/breseq/ANLstock.ACN3578.colony2/breseq_df1972644b/data/output.gd

    Reading input GD file: /storage/synbio/ai_synbio_data/experimental_data/sequencing_orders/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/breseq/ANLstock.ACN3578.colony3/breseq_df1972644b/data/output.gd

    Reading input GD file: /storage/synbio/ai_synbio_data/experimental_data/sequencing_orders/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/breseq/ANLstock.ACN3579.colony1/breseq_df1972644b/data/output.gd

    Reading input GD file: /storage/synbio/ai_synbio_data/experimental_data/sequencing_orders/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/breseq/ANLstock.ACN3579.colony2/breseq_df1972644b/data/output.gd

    Reading input GD file: /storage/synbio/ai_synbio_data/experimental_data/sequencing_orders/Plasmidsaurus_9-13-2025_HTGS8F/Plasmidsaurus_9-13-2025_HTGS8F_Illumina/breseq/ANLstock.ACN3579.colony3/breseq_df1972644b/data/output.gd

    Tabulating frequencies of mutations across all files

    Annotating mutations

    Writing output HTML file: /storage/nspahr/lib_analysis/Plasmidsaurus_9-13-2025_HTGS8F/breseq_analysis_ACN3500/breseq_analysis_ACN3500_NSS/mutation_comparison_ACN3500_NSS.html

*** End ANNOTATE/COMPARE ***

'/storage/nspahr/lib_analysis/Plasmidsaurus_9-13-2025_HTGS8F/breseq_analysis_ACN3500/breseq_analysis_ACN3500_NSS/mutation_comparison_ACN3500_NSS.html'

In [57]:
# Symlinks to library breseq folder
output_symlinks_dir = os.path.join(breseq_ACN3500_dir, 'symlink_to_library_breseq_folder')
os.makedirs(output_symlinks_dir, exist_ok=True)

path_to_folder = short.path / 'breseq'
dst = os.path.join(output_symlinks_dir, 'breseq')
os.symlink(path_to_folder, dst)